### ISSUE TITLE
执行时收到不明报错

### ISSUE THREAD

**Issue by nijinekoyo** [project-mirai/mirai-silk-converter#6]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007fff5a972d30, pid=13536, tid=15596
#
# JRE version: Java(TM) SE Runtime Environment (16.0.2+7) (build 16.0.2+7-67)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (16.0.2+7-67, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3e2d30]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# D:\Dev\golang\BlueArchive\AL1S\Mirai\hs_err_pid13536.log
#
# If you would like to submit a bug report, please visit:
#   https://bugreport.java.com/bugreport/crash.jsp
#
Process exited with 1
```

Windows 11下使用，Mirai版本为2.15.0-M1

**Comment by nijinekoyo** [comment]
插件启动时没有问题，尝试编码发送语音后出现此错误
使用mirai-http-api的websocket协议，将一份wav文件编码为base64后传输

**Comment by cssxsh** [comment]
已有相似 issue
https://github.com/project-mirai/mirai-silk-converter/issues/4

具体的代码问题在
https://github.com/KasukuSakura/silk-codec/pull/3

你可以下载我编译的修复版本 [mirai-silk-converter-0.0.6.mirai.jar](https://github.com/cssxsh/mirai-tts-plugin/releases/download/v1.1.1/mirai-silk-converter-0.0.6.mirai.jar)

**Comment by nijinekoyo** [comment]
> 已有相似 issue #4
> 
> 具体的代码问题在 [KasukuSakura/silk-codec#3](https://github.com/KasukuSakura/silk-codec/pull/3)
> 
> 你可以下载我编译的修复版本 [mirai-silk-converter-0.0.6.mirai.jar](https://github.com/cssxsh/mirai-tts-plugin/releases/download/v1.1.1/mirai-silk-converter-0.0.6.mirai.jar)

这个版本似乎直接不工作了（
我尝试推送语音文件时没有任何反应
Mirai控制台也没打印任何信息

**Comment by cssxsh** [comment]
> 没有任何反应

无意义描述，你什么也不发的结果也是 `没有任何反应`,
如果你的表述无误，就是自己代码本身的问题

你们描述问题总喜欢用概况的方法，把细节都隐藏起来

请确认是以下那种情况
* 日志里有发送语音的记录，但是聊天框没有收到（风控）
* 日志里没有发送语音的记录，但有其他报错 （编码转换错误）

**Comment by nijinekoyo** [comment]
> > 没有任何反应
> 
> 无意义描述，你什么也不发的结果也是 `没有任何反应`, 如果你的表述无误，就是自己代码本身的问题
> 
> 你们描述问题总喜欢用概况的方法，把细节都隐藏起来
> 
> 请确认是以下那种情况
> 
> * 日志里有发送语音的记录，但是聊天框没有收到（风控）
> * 日志里没有发送语音的记录，但有其他报错 （编码转换错误）

我不是故意这么描述的，是真的完全没有一点反应
![image](https://user-images.githubusercontent.com/125987288/233089876-a8491808-418a-44cc-b224-89fcd468620a.png)
按照我代码的设计，发完文字消息后就会发送语音消息，我试了很多遍都不会触发，代码是没有问题的，我如果把插件去掉就会有原版的输出而不会没有一点反应

**Comment by nijinekoyo** [comment]
我在发送后的代码下面添加了同时输出音频文件，输出的音频文件也是正常可以播放的，过程中没有收到任何报错，所以我也很迷（

**Comment by nijinekoyo** [comment]
![image](https://user-images.githubusercontent.com/125987288/233092440-e12c1b9a-f411-4a43-b862-4d7341da3a4a.png)
相同的代码，去除插件后会这样

**Comment by cssxsh** [comment]
> ![image](https://user-images.githubusercontent.com/125987288/233092440-e12c1b9a-f411-4a43-b862-4d7341da3a4a.png) 相同的代码，去除插件后会这样

两个可能性
1. 发的太慢了，一直在后台等待中
2. mirai-api-http 隐藏了报错信息

我倾向于第二种

另外 `22050 Hz` 的 `wav` 默认是不支持转换的 （会报错）具体原因可以见于 https://github.com/KasukuSakura/silk-codec/pull/4
你可以修改 启动脚本 `mcl.cmd` / `mcl.sh` 在 `-jar` 前面加上 `-Dsilk-codec.rate-check-ignore=true`
即 `-Dsilk-codec.rate-check-ignore=true -jar` 以启用

**Comment by nijinekoyo** [comment]
> > ![image](https://user-images.githubusercontent.com/125987288/233092440-e12c1b9a-f411-4a43-b862-4d7341da3a4a.png) 相同的代码，去除插件后会这样
> 
> 两个可能性
> 
> 1. 发的太慢了，一直在后台等待中
> 2. mirai-api-http 隐藏了报错信息
> 
> 我倾向于第二种
> 
> 另外 `22050 Hz·` 的 `wav` 默认是不支持转换的 （会报错）具体原因可以见于 [KasukuSakura/silk-codec#4](https://github.com/KasukuSakura/silk-codec/pull/4) 你可以修改 启动脚本 `mcl.cmd` / `mcl.sh` 在 `-jar` 前面加上 `-Dsilk-codec.rate-check-ignore=true` 即 `-Dsilk-codec.rate-check-ignore=true -jar` 以启用

非常感谢，我在加上`-Dsilk-codec.rate-check-ignore=true`后可以成功转换出音频
可能确实是高赫兹的wav音频转换出错，只不过不报错很奇怪（
